GET http://localhost:5000/posts


###
POST http://localhost:5000/posts
Content-Type: application/json

{
    "title":"Title",
    "message":"New post",
    "creator": "God",
    "tags": ["tag1", "tag2"]
}

###
PATCH http://localhost:5000/posts/61a2430122c211415b47a92c/likePost

###
DELETE http://localhost:5000/posts/61a347793455c5b33a541bc9/deletePost